language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- chmod +x ./gradlew
- "./gradlew --no-daemon startDb"
install:
- "./gradlew --no-daemon createTestDb"
script:
- "./gradlew --no-daemon check"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload"
  on:
    tags: true
env:
  global:
  - secure: LTRUTQZihk0+uBabHnJf1mUl1qdkH9i+emMwOLMkJSli9okP+K0vA8PgYxIVwWqpbGn2jPyfiWXKuWGwhS4rwAUNfwYQbOLXNmKeN6JoLKLgCsINi1+KIsWzw1/IdRPVoaaIszlbroougzlN/qvb1npQHXzA8Zh2asAen11msD3Ve6sdxPSg05aL8dFuO9B6Md6TxMHBenZS5jkOG9JXMaqWZRXuNEnDsk3Me+szGOtUeotgEfrN7vcdk+8M/O1tCwWMBVWbAi2bL16HdhOfahfoFnMqVd36C9uGmPqLSYBQ0AYof597Vfoub8Rx21yMk/BovGCdmJKs5SmxFWCravzlGLzxuxZECEy9CNKXsruwLihxtdCYq/ft7RRK6fO4ScjcOtdAGBzg//WhpwF3Z7eXo6tVtZoOff7cv+OZzbBJIhnYyZJ+BSQOkBRks6iDs26IZxEFzM09eKDFWTCLovEQRuVPGXE0XrXiiC4sTwIDo2nxKYnLQP7JwnPNSDadq5d4BE3PBUh9fd2CKCL1S8kp/8TDRQU1AYfb3of4FYdixjzlipJxt2p8+aJ+X8+o9PaLSSeAoSJO37wWBryGz9hTQVT0XTG6Ohn/edOJOHg+tdwafeT3WTcaqqFrmFkAd5S8uy8pBZij3OBwdr67rEFsaLXD+NpZnZCK7D4tlTk=
  - secure: F+Yp4RURe6ij6rt2V55BsfuWU7ss6qzqG5Coiu8OcCeTr5n3ky3aR6q3eEyMvkoFZ3x6HcmJcDSWYuQ9u6/AcPX+bHkxVaCkYfVVm5YV0IbULjFDKkbiH/o65Mr1dVWSKyC/rOjJgMATa5o7wWyq6E3MwIcjMT2JbR9AQ4MdQusi6csyW+0+Rb8tPWNTRIrd9PlCHFHZJ1Iz54oxyI4LMHa5BBMf/SIVfQ0RwKLS6PCOmHCAVSJsQMllqZu07X+z81Jfz0VCEN2VdR43JIzUhieeVdB/M5aJvn7Y30rKlN2clfJ/ztIHRzgOUgBpeD0b1uVkvEwtqC96HMERRBYAOurpnkzKQaYr9gfV2JDLwmI97VjRqhi1doY9wlBmWkWThkBemE81rVc8/5HB/Creu/K1lAe0BecLrKgpD9GA4uLUPHrD+wlDIBukyg/Z3sQK8o6avc2ghsbfh4MZp2XFGsDRvjtF8LHAeobgBRq/Pq2HIo3l2Fqsq2a1d8ZLFUobtQFo4kvK04XTQHY9qyziRikNDEAgpvtNjPAicbCSw3wT+XhM0hY0kjR+9eT9KX0kuL0sy7mpdjopUOdh4jBpfqP0IS1ruP58aPrhMZ9LUEfLVvHwBlYuEmmsm3i6dtk+KEsYeCVhszPeMLa23y16UA1/AbEuPt47JBi+B3o58Io=
